version: "3"

networks:
  maplon:
    driver: bridge

volumes:
  maplon-postgres:
  maplon-cache:

services:
  maplon-backend:
    image: jsdc2021/maplon-backend-nest:b0.20240219.57
    container_name: maplon-backend
    entrypoint: ["/app/entrypoint/entrypoint.sh"]
    networks:
      - maplon
    volumes:
      - ./storage:/app/storage
    ports:
      - 8080:8080
    depends_on:
      - maplon-postgres

  maplon-cache:
    image: redis:latest
    container_name: maplon-cache
    command: redis-server --save 20 1 --loglevel warning --requirepass ${redis_password}
    volumes:
      - maplon-cache:/data
    networks:
      - maplon

  maplon-postgres:
    image: postgis/postgis:14-3.3
    container_name: maplon-postgres
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      APP_DB_USER: ${postgres_user}
      APP_DB_PASS: ${postgres_password}
      APP_DB_NAME: ${postgres_database}
      PGDATA: /data/postgres
    volumes:
      - ./database-entrypoint:/docker-entrypoint-initdb.d/
      - maplon-postgres:/data/postgres
    networks:
      - maplon

  maplon-pgadmin:
    image: dpage/pgadmin4
    container_name: maplon-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pgadmin_user}@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${pgadmin_password}
    ports:
      - "${pgadmin_port}:80"
    networks:
      - maplon
